In [44]:
import pandas as pd
import numpy as np
import os

In [45]:
cd

/home/mittal


In [46]:
cd/home/mittal/datasets/csv

/home/mittal/datasets/csv


In [48]:
data=pd.read_csv('IRIS.csv')
data

sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [93]:
from sklearn import datasets

In [94]:
X,y=datasets.load_iris("return_x_y=True")

In [95]:
X,y

(array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
        [5

In [96]:
from sklearn.model_selection import train_test_split

In [97]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.33,random_state=4)
X_train,X_test,y_train,y_test

(array([[5.2, 3.5, 1.5, 0.2],
        [5.6, 2.5, 3.9, 1.1],
        [7.7, 2.6, 6.9, 2.3],
        [6.3, 3.4, 5.6, 2.4],
        [6.2, 2.9, 4.3, 1.3],
        [5.7, 2.9, 4.2, 1.3],
        [5. , 3.5, 1.6, 0.6],
        [5.6, 2.9, 3.6, 1.3],
        [6. , 2.2, 5. , 1.5],
        [5.5, 2.6, 4.4, 1.2],
        [4.6, 3.4, 1.4, 0.3],
        [5.6, 3. , 4.1, 1.3],
        [5.1, 3.4, 1.5, 0.2],
        [6.4, 2.9, 4.3, 1.3],
        [6.8, 3. , 5.5, 2.1],
        [6.7, 3. , 5. , 1.7],
        [6.5, 3.2, 5.1, 2. ],
        [6. , 3.4, 4.5, 1.6],
        [4.9, 3.1, 1.5, 0.1],
        [4.9, 2.5, 4.5, 1.7],
        [6.9, 3.2, 5.7, 2.3],
        [5.4, 3.4, 1.5, 0.4],
        [5.5, 2.4, 3.8, 1.1],
        [6.3, 3.3, 6. , 2.5],
        [5. , 3.6, 1.4, 0.2],
        [6.1, 3. , 4.9, 1.8],
        [6.5, 2.8, 4.6, 1.5],
        [5.9, 3. , 5.1, 1.8],
        [6.3, 2.5, 4.9, 1.5],
        [4.9, 3.6, 1.4, 0.1],
        [6.1, 2.6, 5.6, 1.4],
        [6.4, 3.2, 4.5, 1.5],
        [7.1, 3. , 5.9, 2.1],
        [5

In [124]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier()

In [132]:
clf=BaggingClassifier(base_estimator=knn,n_estimators=10,random_state=4,bootstrap=True)

In [134]:
z=clf.fit(X_train,y_train)
z

BaggingClassifier(base_estimator=KNeighborsClassifier(algorithm='auto',
                                                      leaf_size=30,
                                                      metric='minkowski',
                                                      metric_params=None,
                                                      n_jobs=None,
                                                      n_neighbors=5, p=2,
                                                      weights='uniform'),
                  bootstrap=True, bootstrap_features=False, max_features=1.0,
                  max_samples=1.0, n_estimators=10, n_jobs=None,
                  oob_score=False, random_state=4, verbose=0, warm_start=False)

In [135]:
y_pred=clf.predict(X_test)

In [136]:
y_pred

array([2, 0, 2, 2, 2, 1, 2, 0, 0, 2, 0, 0, 0, 1, 2, 0, 1, 0, 0, 2, 0, 2,
       1, 0, 0, 0, 0, 0, 0, 2, 1, 0, 2, 0, 1, 2, 2, 1, 1, 0, 2, 0, 1, 0,
       2, 0, 0, 1, 1, 2])

In [142]:
from sklearn import metrics
accuracy=metrics.accuracy_score(y_pred,y_test)
accuracy

0.98

In [137]:
from sklearn.linear_model import LogisticRegression
logit=LogisticRegression()
clf_1=BaggingClassifier(base_estimator=logit)

In [138]:
clf_1.fit(X_train,y_train)

/home/mittal/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/mittal/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
/home/mittal/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/mittal/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
/home/mittal/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/lo

BaggingClassifier(base_estimator=LogisticRegression(C=1.0, class_weight=None,
                                                    dual=False,
                                                    fit_intercept=True,
                                                    intercept_scaling=1,
                                                    l1_ratio=None, max_iter=100,
                                                    multi_class='warn',
                                                    n_jobs=None, penalty='l2',
                                                    random_state=None,
                                                    solver='warn', tol=0.0001,
                                                    verbose=0,
                                                    warm_start=False),
                  bootstrap=True, bootstrap_features=False, max_features=1.0,
                  max_samples=1.0, n_estimators=10, n_jobs=None,
                  oob_score=False, random_state=None, 

In [139]:
y_pred1=clf_1.predict(X_test)
y_pred

array([2, 0, 2, 2, 2, 1, 2, 0, 0, 2, 0, 0, 0, 1, 2, 0, 1, 0, 0, 2, 0, 2,
       1, 0, 0, 0, 0, 0, 0, 2, 1, 0, 2, 0, 1, 2, 2, 1, 1, 0, 2, 0, 1, 0,
       2, 0, 0, 1, 1, 2])

In [140]:
accuracy1=metrics.accuracy_score(y_pred1,y_test)
accuracy1

0.94

In [162]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import BaggingClassifier

In [163]:
tree=DecisionTreeClassifier()
clf_2=BaggingClassifier(base_estimator=tree)

In [164]:
clf_2.fit(X_train,y_train)

BaggingClassifier(base_estimator=DecisionTreeClassifier(class_weight=None,
                                                        criterion='gini',
                                                        max_depth=None,
                                                        max_features=None,
                                                        max_leaf_nodes=None,
                                                        min_impurity_decrease=0.0,
                                                        min_impurity_split=None,
                                                        min_samples_leaf=1,
                                                        min_samples_split=2,
                                                        min_weight_fraction_leaf=0.0,
                                                        presort=False,
                                                        random_state=None,
                                                        splitter='best'),
    

In [160]:
y_pred2=clf_2.predict(X_test)
y_pred2

array([2, 0, 2, 2, 2, 1, 1, 0, 0, 1, 0, 0, 0, 1, 2, 0, 1, 0, 0, 2, 0, 2,
       1, 0, 0, 0, 0, 0, 0, 2, 1, 0, 2, 0, 1, 2, 2, 1, 1, 0, 2, 0, 1, 0,
       2, 0, 0, 1, 1, 2])

In [161]:
accuracy2=metrics.accuracy_score(y_pred2,y_test)
accuracy2

0.98